### ISSUE TITLE
Criar apresentação

### ISSUE THREAD

**Issue by dedicio** [codenation-dev/squad-2-ad-vuejs-contaazul-1#33]

**Comment by dedicio** [comment]
- colocar dificuldades e soluções relacionadas às que foi escolhido sobre o que foi usado
- planejado vs realizado
- falar sobre pq fizemos backend
- publicar o projeto

**Comment by MarcoshsDreveck** [comment]
Comentários Gabriel e Richard:

- A apresentação deve falar pela forma como nos organizamos e frequencia de conversas
- O porque usamos as bibliotecas
- Planejado vs realizado comparativo
- Trazer o pq do produto 
- E como pensamos para resolver 
- Como quebramos as atividades
- Em tecnologias falar sobre o pq de usarmos cada uma e o que ela resolveria
- Frizar a responsividade
- Fizemos o backend e o pq fizemos

**Comment by lrbtz** [comment]
- Frisar a responsividade do produto
- Roteiro de apresentação do produto
- Padronizar a apresentação com o projeto (cores, fontes, etc)

**Comment by MarcoshsDreveck** [comment]
As tecnologias separar por assunto tipo:
- Quando falar de protótipos... Falar do figma
- Quando falar de organização... Falar do github, google meet, whatsapp
