### ISSUE TITLE
Alterar olho do campo de senha

### ISSUE THREAD

**Issue by dedicio** [codenation-dev/squad-2-ad-vuejs-contaazul-1#61]

**Comment by MarcoshsDreveck** [comment]
Acredito que já esteja funcionando corretamente.

**Comment by lrbtz** [comment]
Eu atualizei a master ontem e pra mim ta trocado.

**Comment by MarcoshsDreveck** [comment]
@lrbtz consegue verificar então ? Pois na minha máquina funciona

**Comment by lrbtz** [comment]
@MarcoshsDreveck acho que eu interpreto o olho de um jeito diferente, tipo, quando aparece a senha o olho estaria aberto, e quando eu fecho o olho aparece a senha com censurada. Talvez seja por isso que eu ache que esteja diferente.

**Comment by MarcoshsDreveck** [comment]
Eu interpreto que é a ação que será feita, tipo visualizar a senha então olho aberto, dai clica e ele muda para o ocultar senha

**Comment by claupimentel** [comment]
O gmail usa da mesma forma que está na master, se o olho ta aberto não mostra a senha, se ta com o risquinho a senha é visível.
