### ISSUE TITLE
Corrigir método de execução do projeto que não funciona no Windows

### ISSUE THREAD

**Issue by dedicio** [codenation-dev/squad-2-ad-vuejs-contaazul-1#64]
atualmente está rodando via: `npm run start`

`(cd backend && npm run start) & npm run serve`

**Comment by MarcoshsDreveck** [comment]
https://itnext.io/4-solutions-to-run-multiple-node-js-or-npm-commands-simultaneously-9edaa6215a93

**Comment by MarcoshsDreveck** [comment]
Configurado "concurrently" na aplicação principal e nodemon no backend para não precisar ficar parando e executando o projeto.
