### ISSUE TITLE
Bug nos 3 pontinhos dos arquivados

### ISSUE THREAD

**Issue by dedicio** [codenation-dev/squad-2-ad-vuejs-contaazul-1#71]
Sempre que redimensiona a janela para um tamanho menor e volta, ele adiciona mais 1 ícone:
![image](https://user-images.githubusercontent.com/38406456/83422895-954c9200-a400-11ea-9f36-b1dd37457480.png)

**Comment by MarcoshsDreveck** [comment]
Mudei o local dos 3 pontinhos... acredito que faça mais sentido ser na barra de busca.
![image](https://user-images.githubusercontent.com/23655540/83515830-5ecc5100-a4ac-11ea-92ab-7a2d71522be2.png)
